
version: "3.8"
services:
  # Redis service
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
    - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - docker-net

  # Postgres service
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${N8N_DB_USERNAME}
      POSTGRES_PASSWORD: ${N8N_DB_PASSWORD}
      POSTGRES_DB: n8ndb
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - docker-net
    ports:
      - "5432:5432"
  # Nginx service
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - docker-net
    depends_on:
      - portainer
      - n8n
      - prometheus
      - elasticsearch
    restart: unless-stopped
  # n8n service
  n8n:
    build:
      context: .
      args:
        GIT_USERNAME: ${GIT_USERNAME}
        GIT_TOKEN: ${GIT_TOKEN}
    container_name: n8n
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - docker-net
    env_file:
      - .env
    environment:
      DB_TYPE: postgres
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8ndb
      DB_POSTGRESDB_USER: ${N8N_DB_USERNAME}
      DB_POSTGRESDB_PASSWORD: ${N8N_DB_PASSWORD}
      DB_POSTGRESDB_SCHEMA: public
      GENERIC_TIMEZONE: Asia/Ho_Chi_Minh
      QUEUE_MODE: redis
      QUEUE_REDIS_HOST: redis
      QUEUE_REDIS_PORT: 6379
      N8N_RUNNERS_ENABLED: true
      N8N_PATH: ${N8N_PATH}
      WEBHOOK_TUNNEL_URL: ${WEBHOOK_TUNNEL_URL}
      WEBHOOK_URL: ${WEBHOOK_URL}
      VUE_APP_PATH: ${VUE_APP_PATH}
      VUE_APP_URL_BASE_API: ${VUE_APP_URL_BASE_API}
      N8N_EDITOR_BASE_URL: ${N8N_EDITOR_BASE_URL}
      N8N_DIAGNOSTICS_ENABLED: false
    restart: unless-stopped
    depends_on:
      - redis
      - postgres

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - docker-net
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    env_file:
      - .env
    environment:
      - PG_HOST= ${PTN_PG_HOST}
      - PG_PORT= ${PTN_PG_PORT}
      - PG_DATABASE= ${PTN_PG_DATABASE}
      - PG_USER= ${PTN_PG_USERNAME}
      - PG_PASSWORD= ${PTN_PG_PASSWORD}
      - REDIS_HOST= ${PTN_REDIS_HOST}
      - REDIS_PORT= ${PTN_REDIS_PORT}
      - REDIS_PASSWORD= ${PTN_REDIS_PASSWORD}
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker-net
    restart: unless-stopped
    depends_on:
      - redis
      - postgres

volumes:
  pg_data:
  n8n_data:
  redis_data:
  elasticsearch_data:
  portainer_data:
  prometheus_data:

networks:
  docker-net:
    driver: bridge