
version: "3.8"
services:
  # Redis service
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
    - "6379:6379"
    volumes:
      - redis_data:/data

  # Postgres service
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${N8N_DB_USERNAME}
      POSTGRES_PASSWORD: ${N8N_DB_PASSWORD}
      POSTGRES_DB: n8ndb
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8"
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # Nginx service
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - n8n
    restart: unless-stopped
  # n8n service
  n8n:
    build:
      context: .
      args:
        GIT_USERNAME: ${GIT_USERNAME}
        GIT_TOKEN: ${GIT_TOKEN}
    container_name: n8n
    volumes:
      - n8n_data:/home/node/.n8n
    env_file:
      - .env
    environment:
      DB_TYPE: postgres
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8ndb
      DB_POSTGRESDB_USER: ${N8N_DB_USERNAME}
      DB_POSTGRESDB_PASSWORD: ${N8N_DB_PASSWORD}
      DB_POSTGRESDB_SCHEMA: public
      GENERIC_TIMEZONE: Asia/Ho_Chi_Minh
      QUEUE_MODE: redis
      QUEUE_REDIS_HOST: redis
      QUEUE_REDIS_PORT: 6379
      N8N_RUNNERS_ENABLED: true
      N8N_PATH: /n8n/
      WEBHOOK_TUNNEL_URL: https://animated-halibut-wrgrq45v7r7c9qgr-80.app.github.dev/n8n/
      WEBHOOK_URL: https://animated-halibut-wrgrq45v7r7c9qgr-80.app.github.dev/n8n/
      VUE_APP_PATH: /n8n/
      VUE_APP_URL_BASE_API: https://animated-halibut-wrgrq45v7r7c9qgr-80.app.github.dev/n8n/
      N8N_EDITOR_BASE_URL: https://animated-halibut-wrgrq45v7r7c9qgr-80.app.github.dev/n8n/
      N8N_DIAGNOSTICS_ENABLED: false
    restart: unless-stopped
    depends_on:
      - redis
      - postgres

volumes:
  pg_data:
  n8n_data:
  redis_data: